### ISSUE TITLE
Data not being captured - AODA sliders

### ISSUE THREAD

**Issue by lharv076** [opennorth/citizenbudgetapp.com#119]
@gmattar @phildionne 

Hi Guillherme, 

Phil is already taking a look, but since you created the sliders I'm also turning to you. 

We have a live consultation, the first since we created the new sliders. tok.citizenbudget.com

When a user moves a slider and submits, their choice isn't being captured. All results are being captured as the default value (default position of the slider), no matter what the users choice was. 

http://ca1.opennorth.ca/admin/questionnaires/570fc5b0a7ceae927000005c

This is affecting all sliders, not just one question.

The other widgets are working fine, so it must have something to do with the new AODA sliders.

It needs to be fixed ASAP! 

Let me know if I can do anything, keep me posted.

Thanks,
Laurence

**Comment by lharv076** [comment]
http://tok.citizenbudget.com/?token=bb24rQj5VFpZDABs2RsQ

**Comment by phildionne** [comment]
After investigation, I'm 99% confident the problem lies here: https://github.com/opennorth/citizenbudgetapp.com/blame/192afbb54381ed7b77791f41600ec3584056573d/app/helpers/application_helper.rb#L144

Here are two screenshots of the form data being POSTed.

This one is from the application prior to https://github.com/opennorth/citizenbudgetapp.com/commit/d604d3523a2eec272b3edd442375af579b79aa8c
![capture d ecran 2016-04-27 a 10 58 31](https://cloud.githubusercontent.com/assets/1047845/14856690/20e14ef4-0c67-11e6-9e36-61976894859b.png)

This one is from the application as of now
![capture d ecran 2016-04-27 a 10 58 48](https://cloud.githubusercontent.com/assets/1047845/14856730/44b4885a-0c67-11e6-8567-d7d02e329d52.png)

Rails expect params in a certain format. Adding the `variables` part is the problem. I have no idea why this has been added or what is the logic behind AODA sliders so I'll leave @gmattar fix this.

**Comment by lharv076** [comment]
@gmattar Any news?

**Comment by lharv076** [comment]
It sounds that this is getting resolved, but in case this might help:

From James:

The hidden input that gets submitted with the form isn't being updated when the slider is moved.

The old code would make that update. I don’t know how to hook into the new code to update that input.

**Comment by lharv076** [comment]
Fixed by #120
