### ISSUE TITLE
Delete data.rake?

### ISSUE THREAD

**Issue by phildionne** [opennorth/citizenbudgetapp.com#96]
@jpmckinney is this file still useful? https://github.com/opennorth/citizenbudgetapp.com/blob/master/lib/tasks/data.rake

I would delete it and the `ruby-progressbar` dependency as well.

**Comment by phildionne** [comment]
I just read [this](https://github.com/opennorth/citizenbudgetapp.com/wiki/Removing-spam%2C-invalid%2C-and-duplicate-responses) and understand what it is doing now. Isn't there better solutions than doing this manually?

One option could be to filter for spam on response submission.

**Comment by jpmckinney** [comment]
For spam, we implemented a honeypot text field which seems to filter all the spam on submission already. I haven't identified new spam with that task in a long time. May be worth keeping around though.

It should be easier to do validation on submission now with PostgreSQL.

I don't see how we can do deduplication at submission. If it's an exact duplicate though, we can do it.

The only thing about duplicates and spam is that we don't want to prevent submission or otherwise notify the user. If the user knows we're filtering, they'll do things smarter until they bypass all our filters.

**Comment by cmonagle** [comment]
Closing in favor of: https://github.com/opennorth/citizenbudgetapp.com/issues/147

**Comment by cmonagle** [comment]
Closing in favor of: https://github.com/opennorth/citizenbudgetapp.com/issues/147
